CREATE TABLE users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(64) NOT NULL,
password VARCHAR(64) NOT NULL,
hoten VARCHAR(128) NOT NULL,
email VARCHAR(128) ,
phonenumber INT(16) UNSIGNED,
avatar VARCHAR(512),
role VARCHAR(10) DEFAULT 'student',
is_deleted BOOLEAN DEFAULT false,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
/*username, password, hoten, email, phonenumber, avatar, role*/
CREATE TABLE message(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
noidung TEXT NOT NULL,
idnguoigui INT(6) UNSIGNED,
idnguoinhan INT(6) UNSIGNED,
is_deleted BOOLEAN DEFAULT false,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE assignment(
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
authorid INT(6) UNSIGNED,
name TEXT,
due DATETIME,
is_deleted BOOLEAN DEFAULT false,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE submission(
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
authorid INT(6) UNSIGNED,
assignmentid INT(10) UNSIGNED,
is_deleted BOOLEAN DEFAULT false,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE game(
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
authorid INT(6) UNSIGNED,
goiy TEXT NOT NULL,
is_deleted BOOLEAN DEFAULT false,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fileattach(
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
part ENUM('assignment','submission','game'),
partid INT(10) UNSIGNED,
tenfile VARCHAR(64),
url VARCHAR(512),
is_deleted BOOLEAN DEFAULT false
);
